samples:
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003103
  run: SRR25558026
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003103/SRR25558026
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003103
  run: SRR25558025
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003103/SRR25558025
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003103
  run: SRR25558015
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003103/SRR25558015
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003103
  run: SRR25558027
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003103/SRR25558027
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003103
  run: SRR25558014
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003103/SRR25558014
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003103
  run: SRR25558013
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003103/SRR25558013
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003104
  run: SRR25557958
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003104/SRR25557958
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003104
  run: SRR25557959
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003104/SRR25557959
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003104
  run: SRR25557957
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003104/SRR25557957
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003105
  run: SRR25556566
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003105/SRR25556566
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003105
  run: SRR25556567
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003105/SRR25556567
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003105
  run: SRR25556565
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003105/SRR25556565
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003105
  run: SRR25556554
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003105/SRR25556554
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003105
  run: SRR25556555
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003105/SRR25556555
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1003105
  run: SRR25556553
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1003105/SRR25556553
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1119183
  run: SRR29258155
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1119183/SRR29258155
- layout: PAIRED
  organism: Mus_musculus
  bioproject: PRJNA1119183
  run: SRR29258154
  path: Pipeline/Projects/PAIRED/Mus_musculus/PRJNA1119183/SRR29258154
- layout: SINGLE
  organism: Mus_musculus
  bioproject: PRJNA868206
  run: SRR21002171
  path: Pipeline/Projects/SINGLE/Mus_musculus/PRJNA868206/SRR21002171
- layout: SINGLE
  organism: Mus_musculus
  bioproject: PRJNA868206
  run: SRR21002170
  path: Pipeline/Projects/SINGLE/Mus_musculus/PRJNA868206/SRR21002170
